#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add postgres user.
#======================================================================================================================

bf-echo "Adding user 'postgres'..."
addgroup --gid 1000 postgres
adduser --uid 1000 --disabled-password --ingroup postgres postgres


#======================================================================================================================
# Add postgres dependencies.
#======================================================================================================================

bf-echo "Installing PostgreSQL dependencies..."
apk --no-cache add \
    icu-libs \
    libcrypto1.1 \
    libldap \
    libpq \
    libssl1.1 \
    libxml2 \
    postgresql-common \
    tzdata


#======================================================================================================================
# Make upgrade script executable.
#======================================================================================================================

bf-echo "Make upgrade script executable..."
chmod +x /upgrade
