#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Executable usage.
#======================================================================================================================

usage () {
    echo "Usage: `basename ${0}` -v VERSION [-m]" 2>&1
    echo "    -m    Mode: 0 = dry run (default), 1 = live."
    echo "    -v    Version to upgrade server to (required)."
    echo "    -h    Show this usage message."
    exit 2
}

while getopts ":hv:m:" C ; do
    case ${C} in
        h) usage ;;
        m) MODE="${OPTARG}" ;;
        v) VERSION="${OPTARG}" ;;
        ?) bf-notok "Invalid option: -${OPTARG}" "upgrade" && usage ;;
    esac
done

shift $(($OPTIND -1))


#======================================================================================================================
# Ensure mode is valid.
#======================================================================================================================

case "${MODE-}" in
    "0"|"") MODE=0 && bf-echo "Dry run mode enabled." "upgrade" ;;
    "1") bf-echo "Live mode enabled." "upgrade" ;;
    "") bf-notok "Mode is required." "upgrade" && usage ;;
    *) bf-notok "Unknown mode: ${MODE-}." "upgrade" && usage ;;
esac


#======================================================================================================================
# Ensure version is valid.
#======================================================================================================================

case "${VERSION-}" in
    "13"|"14") bf-debug "Upgrade to PostgreSQL v${VERSION} is supported." "upgrade" ;;
    "") bf-notok "Version is required." "upgrade" && usage ;;
    *) bf-error "Upgrade to PostgreSQL v${VERSION} is not supported." "upgrade" ;;
esac


#======================================================================================================================
# Ensure version is valid, and check against current version.
#======================================================================================================================

DATA_VERSION=`cat /data/PG_VERSION`
bf-debug "Data version: PostgreSQL v${DATA_VERSION}." "upgrade"

if [ "${DATA_VERSION}" < "${VERSION}" ] ; then
    bf-echo "Upgrading from PostgreSQL v${DATA_VERSION} to v${VERSION}." "upgrade"
else
    bf-error "Unable to upgrade from PostgreSQL v${DATA_VERSION} to v${VERSION}." "upgrade"
fi

exit 0


#======================================================================================================================
# Install the data version.
#======================================================================================================================

bf-echo "Installing PostgreSQL v${DATA_VERSION}..." "upgrade"

apk add --no-cache \
    postgresql${DATA_VERSION}

OLD_BIN="/usr/libexec/postgresql${DATA_VERSION}"
bf-debug "PostgreSQL v${DATA_VERSION} executables installed in ${OLD_BIN}." "upgrade"

bf-done


#======================================================================================================================
# Install the upgrade version.
#======================================================================================================================

bf-echo "Installing PostgreSQL v${VERSION}..." "upgrade"

apk add --no-cache \
    postgresql${VERSION}

NEW_BIN="/usr/libexec/postgresql${VERSION}"
bf-debug "PostgreSQL v${VERSION} executables installed in ${NEW_BIN}." "upgrade"

bf-done

exit 0


#======================================================================================================================
# Create and initialise the new cluster.
#======================================================================================================================

NEW_DATA="/upgrade"
bf-echo "Initialising new cluster in ${NEW_DATA}..." "upgrade"

mkdir ${NEW_DATA} && bf-ch -o postgres:postgres ${NEW_DATA}
s6-setuidgid postgres $BIN/initdb -D ${NEW_DATA}

bf-done


#======================================================================================================================
# Stop the current server.
#======================================================================================================================

bf-echo "Stopping current server..." "upgrade"
s6-setuidgid postgres pg_ctl stop -D "${POSTGRESQL_DATA}"
bf-done


#======================================================================================================================
# Run the upgrade.
#======================================================================================================================

if [ "${MODE}" = "0" ] ; then

    bf-echo "Upgrade dry run..." "upgrade"
    time ${BIN}/pg_upgrade \
        --old-bindir /usr/libexec/postgresql \
        --new-bindir ${BIN} \
        --old-datadir ${POSTGRESQL_DATA} \
        --new-datadir ${NEW_DATA} \
        --clone \
        --check
    bf-done

elif [ "${MODE}" = "1" ] ; then

    bf-echo "Upgrading..." "upgrade"
    time ${BIN}/pg_upgrade \
        --old-bindir /usr/libexec/postgresql \
        --new-bindir ${BIN} \
        --old-datadir ${POSTGRESQL_DATA} \
        --new-datadir ${NEW_DATA} \
        --clone
    bf-done

fi


#======================================================================================================================
# Move old data to subdirectory and new data into correct location.
#======================================================================================================================

OLD_DATA="${POSTGRESQL_DATA}/.old"
bf-echo "Moving old data to ${OLD_DATA}..."
mkdir ${OLD_DATA} && mv ${POSTGRESQL_DATA}/* ${OLD_DATA}
bf-done

bf-echo "Moving new data to ${POSTGRESQL_DATA}..."
mv ${NEW_DATA}/* ${POSTGRESQL_DATA}
bf-done


#======================================================================================================================
# Start the server.
#======================================================================================================================


